baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tom's Hugo Site"
theme = "m10c"


[params]
description = "Just Normal Human Attempting to be a Better Software Developer"
menu_item_separator = "/"
avatar = "phpMlt7JK_c3AM.jpg"
  [params.style]
    darkestColor = "#202c39"
    darkColor = "#283845"
    lightColor = "#b8b08d"
    lightestColor = "#f2d492"
    primaryColor = "#f29559"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "Directoy 1"
    name = "Dir-1"
    url = "/dir1/"
    weight = 4